### ISSUE TITLE
Java and jar on the PATH 

### ISSUE THREAD

**Issue by rfve** [platonai/exotic-amazon#1]
1 - ) what files are these ? where do i need to download ?
                                                       Java and jar on the PATH

2- )     exotic-amazon-main>java -jar target/exotic-amazon*.jar

cmd also gives an error in this command.

Error: Unable to access jarfile target/exotic-amazon*.jar

**Comment by platonai** [comment]
> Java and jar on the PATH

There are a lot of articles on the Internet about installing java :)

> Error: Unable to access jarfile target/exotic-amazon*.jar

Can you paste the full error message? And also tell us your OS information pls.

**Comment by platonai** [comment]
> cmd also gives an error in this command.

Since you are using cmd, wildcar in the command is not supported, you should use the full name:

`java -jar target/exotic-amazon-{the-correct-version}.jar`

**Comment by platonai** [comment]
Proper instructions are added in README.
