### ISSUE TITLE
Failed to create chrome devtools driver

### ISSUE THREAD

**Issue by zngpng** [platonai/exotic-amazon#16]
请问作者有遇到这个情况嘛？能否提供一下思路，3q
 
`[r-worker-3] WARN  a.p.p.p.b.e.context.WebDriverContext - 304. Retry task 235 in crawl scope | caused by: [Unexpected] Failed to create chrome devtools driver`

**Comment by platonai** [comment]
1. Check your chrome version number, [100, 110] are supported by now, 111 is not supported which is reported by  @sskmtm in #14 
2. If the error occurs occasionally and your crawler is still working, you can just ignore it. The system is designed to create and destroy chrome processes very frequently.
3. There are many possible causes:
    1. no memory
    2. no hard disk
    4. other resource exhaustion

To better tracking the issue, please:
1. tell us the version number of your exotic-amazon
5. paste the detailed error message

**Comment by platonai** [comment]
Will be fixed in the next version with pulsar-1.10.11.

**Comment by platonai** [comment]
Fixed in the main branch by upgrade pulsar to 1.10.11.
