### ISSUE TITLE
The proxy is expired (xxx), context reset will be triggered

### ISSUE THREAD

**Issue by sskmtm** [platonai/exotic-amazon#19]
使用代理的时候，发现了以下错误：

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/113836233/227953468-5c0d15b2-e13a-45d4-817c-21148790d896.png">

我的理解是代理过期了会自动重新获取的吧，不知道为什么一直卡在这个错误

导致：`⬆ U for RT got 1601 0 <- 0 in 0s`

**Comment by platonai** [comment]
同一个IP反复出现这个错误吗？

**Comment by sskmtm** [comment]
pulsarR-1.10.X 对于 exotic-amazon 存在破坏性更新吧

`<pulsar.version>1.9.9</pulsar.version>` ---> `<pulsar.version>1.10.3</pulsar.version>` 

会发生一系列错误：
<img width="651" alt="image" src="https://user-images.githubusercontent.com/113836233/228424160-a8585ddf-09a0-476f-8402-51f4ae3bc548.png">

另外本来想使用 main 分支的代码，但是发生了另外的错误，详见： [https://github.com/platonai/exotic-amazon/issues/20](https://github.com/platonai/exotic-amazon/issues/20)

**Comment by platonai** [comment]
Exotic-amazon-0.1.x 目前已经将 pulsar 升级到了最新的 1.9.19，可以试试。如果还有其他问题，那么还是建议直接使用 Exotic-amazon-main.
