### ISSUE TITLE
why can't I get it to work somehow :(

### ISSUE THREAD

**Issue by rfve** [platonai/exotic-amazon#2]
i read the instructions in the readme.

 i got this result when I wrote the following code in cmd.

**cd exotic-amazon && mvn -DskipTests=true**

https://snipboard.io/LSYQ9r.jpg

`[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< ai.platon.exotic:exotic-amazon >-------------------
[INFO] Building Exotic Amazon 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for ai.platon.pulsar:pulsar-h2:jar:1.4.196 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.652 s
[INFO] Finished at: 2022-10-06T13:54:19+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project exotic-amazon: Could not resolve dependencies for project ai.platon.exotic:exotic-amazon:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at ai.platon.scent:scent-resources:jar:1.9.7: Failed to read artifact descriptor for ai.platon.scent:scent-resources:jar:1.9.7: Could not transfer artifact ai.platon.scent:scent-resources:pom:1.9.7 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [platon.ai (http://static.platonic.fun/repo/, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

secondly, when I wrote this code, I got the following result. i think he can't find this file.

**java -jar target/exotic-amazon*.jar**

```
C:\js\exotic-amazon>java -jar target/exotic-amazon*.jar
Error: Unable to access jarfile target/exotic-amazon*.jar
```
or

```
C:\js\exotic-amazon>java -jar target/exotic-amazon.jar
Error: Unable to access jarfile target/exotic-amazon.jar
```

or java -jar target/exotic-amazon-19.jar
```

C:\js\exotic-amazon>java -jar target/exotic-amazon-19.jar
Error: Unable to access jarfile target/exotic-amazon-19.jar
```

the exotic-amazon.jar file is not in the share here. do we need to download it from somewhere else ?

also, this link does not work for me. I think something's missing.
`Open [System Glances](http://localhost:8182/api/system/status/glances) to see the system status at a glance.
`

**Comment by platonai** [comment]
> Failed to read artifact descriptor for ai.platon.scent, ..., Blocked mirror for repositories
Here is why and how to fix:

https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositories

Search **maven-default-http-blocker** to learn more. Good luck!

> the exotic-amazon.jar file is not in the share here.

You should use the full name of the jar on Windows (as mentioned in README):
java -jar target/exotic-amazon-{the-actual-version}.jar

You can use command dir on windows to show the full name.

> also, this link does not work for me.
It works only when the program is started :)

**Comment by rfve** [comment]
> > the exotic-amazon.jar file is not in the share here.

hello ,
I also wrote about it on github. but I still can't run the program. the exotic-amazon.jar file mentioned in the program is not in the rar file I downloaded from the github repository.

where can I download the exotic-amazon.jar  file? 


https://github.com/platonai/exotic-amazon


i also can't get over the error below. can you help please ...

**Comment by rfve** [comment]
new problem ,

i downloaded the files from the link below.
http://static.platonic.fun/repo/ai/platon/exotic/

exotic-standalone-1.10.4.jar 
exotic-standalone.jar	 
exotic.war

and I put it inside the exotic-amazon folder. when I type the command, I get the following error.


`java -jar exotic-standalone-1.10.4.jar harvest https://www.amazon.com/Best-Sellers-Automotive/zgbs/automotive/ -outLink a[href~=/dp/] -component "#centerCol" -component "#buybox"`

error message ;
https://snipboard.io/23aeVM.jpg

**Comment by platonai** [comment]
> where can I download the exotic-amazon.jar  file?

We do not provide a exotic-amazon.jar to download, you should build the project yourself.

`java -jar target/exotic-amazon-{the-actual-version}.jar`

NOTICE {the-actual-version} !!

**Comment by platonai** [comment]
> exotic-standalone-1.10.4.jar
> exotic-standalone.jar
> exotic.war

They have nothing to do with exotic-amazon, they wer developed for other purposes.

Just carefully and patiently follow the README to build the project.

**Comment by platonai** [comment]
You did not handle the **maven-default-http-blocker problem**, as I mentioned in my [first comment](https://github.com/platonai/exotic-amazon/issues/2#issuecomment-1269987984).

Again, I sugguest you to follow the README file, CAREFULLY AND PATIENTLY !!!
