### ISSUE TITLE
Failed to create proxy context - No proxy found in pool LoadingProxyPool

### ISSUE THREAD

**Issue by sskmtm** [platonai/exotic-amazon#21]
pom.xml 依赖版本变更后：
```plain
# 修改前
<pulsar.version>1.9.9</pulsar.version>
<scent.version>1.9.7</scent.version>

# 修改后
<pulsar.version>1.10.11</pulsar.version>
<scent.version>1.10.4</scent.version>
```

使用代理出现如下错误：

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/113836233/228456717-6ab2668f-7003-4548-8e14-9465fac26d1d.png">

请问这种情况我该怎么解决呢？

**Comment by platonai** [comment]
Exotic-amazon-0.1.x 不建议使用 pulsar-1.10.x，我们没有测试过；Exotic-amazon-0.1.x 目前已经将 pulsar 升级到了最新的 1.9.19，可以试试。如果还有其他问题，那么还是建议直接使用 Exotic-amazon-main.

**Comment by sskmtm** [comment]
> Exotic-amazon-0.1.x 不建议使用 pulsar-1.10.x，我们没有测试过；Exotic-amazon-0.1.x 目前已经将 pulsar 升级到了最新的 1.9.19，可以试试。如果还有其他问题，那么还是建议直接使用 Exotic-amazon-main.

刚测试了 1.9.19:
```plain
<pulsar.version>1.9.19</pulsar.version>
<scent.version>1.9.10</scent.version>
```

还是会出现如下错误：
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/113836233/228529482-0fb69a23-f43f-4180-895b-24558a2de2e2.png">

**Comment by platonai** [comment]
Exotic-amazon-0.1.x 没有这个重现 No proxy found 问题。
