### ISSUE TITLE
启动报错 Parameter 7 of constructor in ai.platon.exotic.amazon.starter.CrawlApplication required a bean of type 'ai.platon.scent.protocol.browser.emulator.context.BrowserPrivacyContextMonitor' that could not be found.

### ISSUE THREAD

**Issue by KevinMyDing** [platonai/exotic-amazon#34]
启动的时候出现错误:
Parameter 7 of constructor in ai.platon.exotic.amazon.starter.CrawlApplication required a bean of type 'ai.platon.scent.protocol.browser.emulator.context.BrowserPrivacyContextMonitor' that could not be found.

这个该如何解决呢?

**Comment by platonai** [comment]
Try pull the latest main branch again please, we have just updated the main branch.

**Comment by platonai** [comment]
Fixed
