### ISSUE TITLE
大佬能不能简单讲讲怎么用？

### ISSUE THREAD

**Issue by ZhujingJava** [platonai/exotic-amazon#36]
我这边已经构建完了运行上了，但是不知道从何入手，是运行jar包就开始抓数据吗？还是通过post url来抓取？
也找不到api文档，求大佬指点一二

**Comment by hughkiller002** [comment]
运行jar包你不就看到它在开浏览器了嘛，文档有说去哪个文件夹，里面json就是抓下来的文件，然后看看源码不够用自己在加点
